on:
  workflow_call:
    secrets:
      SECRET_SSH_KEY:  { required: true }
      SECRET_SSH_HOST: { required: true }
      SECRET_SSH_USER: { required: true }
  workflow_dispatch:

jobs:
  pull-and-up:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Validate PROJECT_NAME variable
        run: |
          if [ -z "${{ vars.PROJECT_NAME }}" ]; then
            echo "ERROR: variable 'PROJECT_NAME' is missing or empty!"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SECRET_SSH_KEY }}

      - name: Add remote server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SECRET_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Execute target service sync
        env:
          SSH_REMOTE: "${{ secrets.SECRET_SSH_USER }}@${{ secrets.SECRET_SSH_HOST }}"
        run: |
          DEPLOY_DIR="/opt/${{ vars.PROJECT_NAME }}/prod"
          ( set -x; rsync -az --mkpath docker/compose/ ${SSH_REMOTE}:${DEPLOY_DIR}/ ) || exit 1

          ssh $SSH_REMOTE "
            echo '${{ secrets.GITHUB_TOKEN }}' | ( set -x; docker login ghcr.io -u ${{ github.actor }} --password-stdin )

            ( set -x; docker compose -f ${DEPLOY_DIR}/docker-compose.base.yaml --project-directory ${DEPLOY_DIR} pull ) || exit 1
            ( set -x; docker image prune -f ) || exit 1
          "
