on:
  workflow_dispatch:
  workflow_call:
    secrets:
      SECRET_SSH_KEY:
        required: true
      SECRET_SSH_HOST:
        required: true
      SECRET_SSH_USER:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Configuration
        run: |
          [ -n "${{ secrets.SECRET_SSH_KEY }}" ] || { echo "ERROR: secret.SECRET_SSH_KEY is empty"; exit 1; }
          [ -n "${{ secrets.SECRET_SSH_HOST }}" ] || { echo "ERROR: secret.SECRET_SSH_HOST is empty"; exit 1; }
          [ -n "${{ secrets.SECRET_SSH_USER }}" ] || { echo "ERROR: secret.SECRET_SSH_USER is empty"; exit 1; }

      - name: Set up SSH agent and keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SECRET_SSH_KEY }}

      - name: Add remote server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SECRET_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Execute remote deployment
        env:
          SSH_REMOTE: "${{ secrets.SECRET_SSH_USER }}@${{ secrets.SECRET_SSH_HOST }}"
        run: |
          DEPLOY_DIR="/opt/${{ github.event.repository.name }}"

          ( set -x; ssh $SSH_REMOTE "sudo mkdir -p ${DEPLOY_DIR} && sudo chown -R ${{ secrets.SECRET_SSH_USER }} ${DEPLOY_DIR}" ) || exit
          ( set -x; scp docker/compose/docker-compose.prod.yaml ${SSH_REMOTE}:${DEPLOY_DIR}/docker-compose.prod.yaml ) || exit

          ssh $SSH_REMOTE "
            echo '${{ secrets.GITHUB_TOKEN }}' | ( set -x; docker login ghcr.io -u ${{ github.actor }} --password-stdin )

            ( set -x; docker compose -f ${DEPLOY_DIR}/docker-compose.prod.yaml --project-directory ${DEPLOY_DIR} pull ) || exit
            ( set -x; docker compose -f ${DEPLOY_DIR}/docker-compose.prod.yaml --project-directory ${DEPLOY_DIR} up -d --remove-orphans ) || exit
            ( set -x; docker image prune -f ) || exit
          "
