on:
  workflow_call:
  workflow_dispatch:

jobs:
  docker_compose_build_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Log in to GHCR
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build via Docker Compose
        run: |
          docker compose -f docker/compose/docker-compose.base.yaml build
          docker compose -f docker/compose/docker-compose.base.yaml push
