name: docker-compose-prod-185.221.213.245

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      image_name:
        type: string
        required: true
      image_tag:
        type: string
        required: true
      dockerfile:
        type: string
        required: true

# https://github.com/petrochenkov-ak-lab/.github/settings/secrets/actions
# IP_185_221_213_245_SSH_KEY ~/.ssh/keys/185.221.213.245/user2845bb32d13551897dd1f814
jobs:
  validate-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check server secrets
        env:
          KEY: ${{ secrets.IP_185_221_213_245_SSH_KEY }}
        run: |
          [ -n "$KEY" ] || { echo "ERROR: Secret IP_185_221_213_245_SSH_KEY is empty or not found!"; exit 1; }
          echo "SUCCESS: All secrets for 185.221.213.245 are valid."

  run-deploy:
    uses: ./.github/workflows/docker-compose-prod.yml
    with:
      image_name: ${{ inputs.image_name }}
      image_tag: ${{ inputs.image_tag }}
      dockerfile: ${{ inputs.dockerfile }}
    secrets:
      SSH_KEY: ${{ secrets.IP_185_221_213_245_SSH_KEY }}
      SSH_HOST: '185.221.213.245'
      SSH_USER: 'user2845bb32d13551897dd1f814'
