name: docker-compose-prod.yml

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
    secrets:
      SSH_KEY:
        required: true
      SSH_HOST:
        required: true
      SSH_USER:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Configuration
        run: |
          [ -n "${{ secrets.SSH_KEY }}" ] || { echo "ERROR: secret.SSH_KEY is empty"; exit 1; }
          [ -n "${{ secrets.SSH_HOST }}" ] || { echo "ERROR: secret.SSH_HOST is empty"; exit 1; }
          [ -n "${{ secrets.SSH_USER }}" ] || { echo "ERROR: secret.SSH_USER is empty"; exit 1; }
          [ -n "${{ vars.COMPOSE_PROJECT_NAME }}" ] || { echo "ERROR: vars.COMPOSE_PROJECT_NAME is empty"; exit 1; }

      - name: Create runtime .env file
        working-directory: docker/compose/prod
        run: |
          echo "IMAGE_NAME=${{ inputs.image_name }}" >> .env
          echo "IMAGE_TAG=${{ inputs.image_tag }}" >> .env
          echo "COMPOSE_PROJECT_NAME=${{ vars.COMPOSE_PROJECT_NAME }}" >> .env
          echo "DJANGO_PORT=8000" >> .env

      - name: Copy files to Remote Server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker/compose/prod/docker-compose.yaml,docker/compose/prod/.env"
          target: "~/app-deploy"
          strip_components: 3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app-deploy
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            sudo docker compose pull
            sudo docker compose up -d --remove-orphans
